application: arellecmd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: arelle/images

- url: /favicon.ico
  static_files: arelle/images/arelle.ico
  upload: arelle/images/arelle.ico

- url: /.*
  script: arelleCmdLine.py

libraries:
- name:    PIL
  version: "latest"

- name:    lxml
  version: "latest"